"""first one

Revision ID: 18cd87a870e0
Revises: 
Create Date: 2019-10-06 12:34:18.331508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cd87a870e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('front_left_weel', sa.Float(), nullable=False),
    sa.Column('front_right_weel', sa.Float(), nullable=False),
    sa.Column('back_left_weel', sa.Float(), nullable=False),
    sa.Column('back_right_weel', sa.Float(), nullable=False),
    sa.Column('servo_angle', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement')
    # ### end Alembic commands ###
